[package]
name = "pathwalker"
version = "0.1.2"
edition = "2021"
authors = ["Nils Feierabend <mztikk@outlook.de>"]
repository = "https://github.com/mztikk/pathwalker"
license = "MIT"
description = "library to walk path"
