[package]
name = "pathwalker"
version = "0.2.4"
edition = "2021"
authors = ["Nils Feierabend <mztikk@outlook.de>"]
repository = "https://github.com/mztikk/pathwalker"
license = "MIT"
description = "library to walk path"

[dependencies]
pathfilter = { version = "0.3.1", optional = true }
